### ISSUE TITLE
CHECKPATCH_COMMAND not working?

### ISSUE THREAD

**Issue by MatiasElo** [webispy/helloworld-docker-action#9]
Hi,

I'm having trouble when trying to use a custom checkpatch script with the `CHECKPATCH_COMMAND` env variable. Setting the variable doesn't seem to have any effect and the standard `checkpatch.pl` script is always used.

Below is a snippet from our config. `./scripts/checkpatch.pl` is a modified checkpatch script in our repo.

```
jobs:
  Checkpatch:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt install codespell

    - name: Check pull request
      if: github.event_name == 'pull_request'
      env:
        CHECKPATCH_COMMAND: ./scripts/checkpatch.pl
      uses: webispy/checkpatch-action@v6
```
